In [462]:
from SPARQLWrapper import SPARQLWrapper, JSON
import pandas as pd

In [463]:
#carichiamo il csv con i soggetti di Wikidata
df_wikidata = pd.read_csv("wd_dataset.csv", encoding="utf-8")

df_wikidata.head(3)

,entity,label,aliases,description,category
0,http://www.wikidata.org/entity/Q304227,Aba,NaN,ninfa naiade della mitologia greca,greek_deity
1,http://www.wikidata.org/entity/Q279782,Abarbarea,NaN,naiade della mitologia greca,greek_deity
2,http://www.wikidata.org/entity/Q2370052,Acanto,NaN,"personaggio della mitologia greca, probabilmente una ninfa amata da Apollo",greek_deity

In [464]:
#estraggo tutte le label  
labels = (
    df_wikidata["label"]
    .dropna() #tolgo i valori nulli
    .str.strip() #tolgo gli spazi bianchi all'inizio e alla fine
    .tolist() #converto in lista

)

#estraggo gli aliases separando quelli multipli
aliases = []
for alias_str in df_wikidata["aliases"].dropna(): #per ogni stringa di alias che non è nulla
    alias_list = [alias.strip() for alias in alias_str.split(",")] #separo gli alias con la virgola, tolgo gli spazi e metto tutto in minuscolo
    aliases.extend(alias_list) #aggiungo alla lista totale degli alias

#unisco tutto 
myth_terms = list(set(labels + aliases)) #unisco le label e gli alias, tolgo i duplicati con set e riconverto in lista
len(myth_terms)

3121

In [465]:
#ENDPOINT SPARLQ DI ARCO 
arco_endpoint = "https://dati.cultura.gov.it/sparql"

sparql_arco = SPARQLWrapper(arco_endpoint)
sparql_arco.setReturnFormat(JSON)

In [466]:
# NUMERO TOTALE DEI BENI STORICO ARTISTICI - senza duplicati 
query1 = """
PREFIX arco: <https://w3id.org/arco/ontology/arco/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT (COUNT(DISTINCT ?item) AS ?totalItems)
WHERE {
  ?item rdf:type <https://w3id.org/arco/ontology/arco/HistoricOrArtisticProperty> .
}
"""


sparql_arco.setQuery(query1)
results = sparql_arco.query().convert()

for result in results["results"]["bindings"]:
    print(f"Total Historic or Artistic Properties: {result['totalItems']['value']}")

Total Historic or Artistic Properties: 2258640

In [468]:
#query pr estrarre i dati dei beni storico artistici in batch 
# Iterare su tutti i 2.258.640 beni con batch di 20000

rows = []
batch_size = 20000
total_items = 2258640

for offset in range(0, total_items, batch_size):
    print(f"Processando batch: offset={offset}, items processati={len(rows)}")
    
    query2 = f"""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX a-cd: <https://w3id.org/arco/ontology/context-description/>

SELECT ?item ?subject ?label
WHERE {{

  ?item rdf:type <https://w3id.org/arco/ontology/arco/HistoricOrArtisticProperty> .
  
  OPTIONAL {{ ?item rdfs:label ?label . }}

  OPTIONAL {{ ?item a-cd:subject ?subject . }}

}}
LIMIT {batch_size}
OFFSET {offset}
"""
    
    sparql_arco.setQuery(query2)
    results = sparql_arco.query().convert()
    
    # estrai i dati da questo batch
    for r in results["results"]["bindings"]:
        rows.append({
            "item": r["item"]["value"] if "item" in r else None,
            "label": r["label"]["value"] if "label" in r else None,
            "subject": r["subject"]["value"] if "subject" in r else None
        })
    
    # se il batch è vuoto, ferma il loop
    if len(results["results"]["bindings"]) < batch_size:
        print(f"Batch incompleto ({len(results['results']['bindings'])} items), fine loop")
        break

Processando batch: offset=0, items processati=0
Processando batch: offset=20000, items processati=20000
Processando batch: offset=40000, items processati=40000
Processando batch: offset=60000, items processati=60000
Processando batch: offset=80000, items processati=80000
Processando batch: offset=100000, items processati=100000
Processando batch: offset=120000, items processati=120000
Processando batch: offset=140000, items processati=140000
Processando batch: offset=160000, items processati=160000
Processando batch: offset=180000, items processati=180000
Processando batch: offset=200000, items processati=200000
Processando batch: offset=220000, items processati=220000
Processando batch: offset=240000, items processati=240000
Processando batch: offset=260000, items processati=260000
Processando batch: offset=280000, items processati=280000
Processando batch: offset=300000, items processati=300000
Processando batch: offset=320000, items processati=320000
Processando batch: offset=340000, items processati=340000
Processando batch: offset=360000, items processati=360000
Processando batch: offset=380000, items processati=380000
Processando batch: offset=400000, items processati=400000
Processando batch: offset=420000, items processati=420000
Processando batch: offset=440000, items processati=440000
Processando batch: offset=460000, items processati=460000
Processando batch: offset=480000, items processati=480000
Processando batch: offset=500000, items processati=500000
Processando batch: offset=520000, items processati=520000
Processando batch: offset=540000, items processati=540000
Processando batch: offset=560000, items processati=560000
Processando batch: offset=580000, items processati=580000
Processando batch: offset=600000, items processati=600000
Processando batch: offset=620000, items processati=620000
Processando batch: offset=640000, items processati=640000
Processando batch: offset=660000, items processati=660000
Processando batch: offset=680000, items processati=680000

URLError: <urlopen error [WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto>

In [ ]:
# i rows sono già stati accumulati dal loop nel batch precedente
# creiamo il dataframe consolidato
df_arco = pd.DataFrame(rows)
df_arco = df_arco.drop_duplicates(subset="item")

print(f"Righe totali in df_arco : {len(df_arco)}")
df_arco[["item", "label", "subject"]].head(1)

Righe totali in df_arco : 1120195

,item,label,subject
0,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704280,"Arlecchino primordiale. Fine del cinquecento. Martinelli, figurino per costume di scena, maschile (disegno) by Fo, Dario (XX)","figurino per costume di scena, maschile"

In [ ]:
import re

# 1. filtro base (toglie null)
df_arco = df_arco[df_arco["subject"].notna()].copy()

#TERMINI DA ESCLUDERE TOTALMENTE  
ignore_subjects = [
    "Acheo","Africa","Agatone","Aia","Aix","Alessandro","Alessi","Angelo","Aniceto","Anna","Antenore","Antioco","Api","Arche","Archelao","Armeno","Astarte","Asteria","Asterio","Asia","Argia","Astaco","Atteo","Aula","Aventino","Basile","Bolina","Bronte","Calice","Camilla", "Canto","Capeto","Car",
    "Cassandra","Cerano", "Cino","Cleopatra","Cocito","Como", "Copia","Corinto","Coro","Creta", "Damaso","Delfino", "Egisto","Egitto","Egle","Elea", "Eleuteria", "Eleutero", "Elia","Elios","Emo", "Epulone","Erme","Eschilo","Esione","Etna", "Etolo", "Ezio", "Fante", "Fenice", "Festo", "Finta",
    "Giacinto", "Giano", "Grillo", "Greco", "Idra", "Ippolita", "Leo"

]


df_arco = df_arco[
    ~df_arco["subject"].str.contains(
        "|".join(ignore_subjects),
        case=False,
        na=False
    )
]


terms = [
    re.escape(t)
    for t in myth_terms
    if isinstance(t, str)
    and t.strip() != ""
    and t[0].isupper()
]

# regex unica case-sensitive (matching esatto)
pattern = r'(?<![A-Za-zÀ-ÿ])(' + '|'.join(terms) + r')(?![A-Za-zÀ-ÿ-])'
regex = re.compile(pattern)


#TERMINI DA ACCETTARE SOLO SE COMPAIONO INSIEME A QUESTE PAROLE []
context_rules = {
    "Ascanio" : ["fuoco", "cervo"],
    "Callisto": ["Arcade", "Diana"],
    "Concordia": ["Allegoria", "Innocenza", "Giustizia"],
    "Cornacchia": ["metamorfosi"],
    "Egeo": ["Teseo"],
    "Elena": ["ratto"],
    "Ettore": ["morte", "Protesilao", "Achille", "Andromaca", "Paride"],
    "Europa": ["ratto", "Toro", "sibilla", "mito","allegoria","ancelle","leone"],
    "Grazie" : ["tre", "danzanti"],
    "Ida" : ["Linceo"],
    "Ippolito":["episodi", "caduta", "morte"]
}


# TERMINI DA ESCLUDERE SE COMPAIONO CON DETERMINATE PAROLE
exclusion_rules = {
    "Abbondanza": ["Santa", "Sant"],
    "Amore": ["Dio", "Madonna", "castello", "fontana"],
    "Carità": ["Santa", "Sant", "Maria"],
    "Diana" : ["Beata", "duca"],
    "Dioniso": ["Vescovo"],
    "Elio" : ["ponte","ritratto","paesaggio", "veduta"],
    "Enea": ["Beato", "discepolo"],
    "Ercole": ["Ricotti", "Dandini", "Comini", "Farnese"],
    "Ermes" : ["ritratto"],
    "Fede" : ["santi", "sant", "san", "dottrina", "biblici", "Francia", "cattolica", "madonna", "evangelisti", "religione", "dio", "angeli", "angioletti","santa", "papa", "santo", "cristiana"],
    "Giustizia" : ["porta", "palazzo", "misericordia", "san", "santa", "papa", "imperatore", "papale"],
    "Gorgone" : ["santa"],
    "Io": ["ritratti "],
    "Lavinia":["ritratto", "autoritratto"],
    "Leandro" : ["autoritratto", "San", "busto", "torre"]

}


def validate_matches(row):

    subject = row["subject"]

    valid_matches = []

    for match in row["matched_term"]:

        # PRIMO CHECK: controlla se il termine è nelle exclusion_rules
        if match in exclusion_rules:
            exclusion_keywords = exclusion_rules[match]
            # se almeno una parola di esclusione è presente, scarta il termine
            if any(re.search(r'\b' + re.escape(k) + r'\b', subject, re.IGNORECASE) for k in exclusion_keywords):
                continue  # salta questo match, non lo aggiungere a valid_matches
        
        # SECONDO CHECK: controlla context_rules (inclusione condizionata)
        # se il termine non ha regole → tienilo
        if match not in context_rules:
            valid_matches.append(match)
            continue

        # controlla parole contestuali con word boundaries (parole intere)
        keywords = context_rules[match]

        if any(re.search(r'\b' + re.escape(k) + r'\b', subject, re.IGNORECASE) for k in keywords):
            valid_matches.append(match)

    return valid_matches


df_arco["matched_term"] = df_arco["subject"].str.findall(regex)
# matching veloce
df_arco["matched_term"] = df_arco.apply(validate_matches, axis=1)

# solo match
df_matches = df_arco[df_arco["matched_term"].str.len() > 0]

In [ ]:
# Verifica i risultati
print(f"Totale beni Arco: {len(df_arco)}")
print(f"Beni con match mitologico: {len(df_matches)}")

Totale beni Arco: 460102
Beni con match mitologico: 11551

In [ ]:
pd.set_option("display.max_colwidth", None)

start = 5200
end = 5400

#SONO ARRIVATA A "LIDO"

df_matches_sorted = df_matches.sort_values("matched_term")

df_matches_sorted[["item","label", "subject", "matched_term"]].iloc[start:end]

,item,label,subject,matched_term
1797516,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0300182761,"Leda e il cigno (disegno, opera isolata) di Cosway Richard (sec. XIX)",Leda e il cigno,[Leda e il cigno]
1797628,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0300182817,"Leda e il cigno (disegno, opera isolata) di Cosway Richard (sec. XIX)",Leda e il cigno,[Leda e il cigno]
2007322,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900768831,"Leda, Leda e il cigno (statuetta, opera isolata) di Cassioli Giovanni (attribuito) (sec. XX)",Leda e il cigno,[Leda e il cigno]
2205476,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0300140197,"Leda e il cigno (dipinto, opera isolata) - ambito mantovano (seconda metà sec. XVIII)",Leda e il cigno,[Leda e il cigno]
355538,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900281624-7,Leda e il cigno (dipinto) by Tommaso di Battista del Verrocchio (sec. XVI),Leda e il cigno,[Leda e il cigno]
475888,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900281646-1_13,Leda e il cigno (dipinto) by Marchetti Marco detto Marco da Faenza (sec. XVI),Leda e il cigno,[Leda e il cigno]
2061572,https://w3id.org/arco/resource/Lombardia/HistoricOrArtisticProperty/P0120-00231_R03,Leda e il cigno (disegno) by Gallina Gallo (secondo quarto sec. XIX),Leda e il cigno,[Leda e il cigno]
678792,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0800285522,Leda e il cigno (gemma) - produzione romana (sec. I a.C),Leda e il cigno,[Leda e il cigno]
601896,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1500334144,Leda e il cigno (disegno) - ambito italiano (sec. XIX),Leda e il cigno,[Leda e il cigno]
355862,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900281662-3,Leda e il cigno (dipinto) by Marchetti Marco detto Marco da Faenza (sec. XVI),Leda e il cigno,[Leda e il cigno]
2061566,https://w3id.org/arco/resource/Lombardia/HistoricOrArtisticProperty/P0120-00220_R03,Leda e il cigno (disegno) di Gallina Gallo (prima metà sec. XIX),Leda e il cigno,[Leda e il cigno]
373314,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1100209339-21,Leda e il cigno (decorazione plastica) by Brandani Federico (sec. XVI),Leda e il cigno,[Leda e il cigno]
1012966,https://w3id.org/arco/resource/SARDEGNA/HistoricOrArtisticProperty/2000225540,"Leda con il cigno, Leda e il cigno (scultura) by Cappellini Sergio (sec. XX)",Leda e il cigno,[Leda e il cigno]
177472,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500292036,"Leda e il cigno (stampa smarginata, serie) di Piazzetta Giovanni Battista (sec. XVIII)",Leda e il cigno,[Leda e il cigno]
2215924,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500311857,Leda e il cigno (scultura) - ambito veneto (metà sec. XVIII),Leda e il cigno,[Leda e il cigno]
2047990,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1600105888,Leda e il cigno (soffietto) - ambito italiano (sec. XVII),Leda e il cigno,[Leda e il cigno]
678138,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0800233242,Leda e il cigno (dipinto) - ambito reggiano (prima metà sec. XIX),Leda e il cigno,[Leda e il cigno]
738554,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1500569710,Leda e il cigno (disegno) di Abbate Giuseppe (secondo quarto sec. XIX),Leda e il cigno,[Leda e il cigno]
373500,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1100209343-4,Leda e il cigno (decorazione plastica) di Brandani Federico (e aiuti) (sec. XVI),Leda e il cigno,[Leda e il cigno]
355742,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900281643-8,Leda e il cigno (dipinto) by Marchetti Marco detto Marco da Faenza (sec. XVI),Leda e il cigno,[Leda e il cigno]
757288,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0300643649,Leda e il cigno (dipinto) - ambito romano (sec. XVI),Leda e il cigno,[Leda e il cigno]
682178,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900014171,Leda e il cigno (rilievo) di Bandinelli Bartolomeo detto Baccio Bandinelli (metà sec. XVI),Leda e il cigno,[Leda e il cigno]
311618,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500073443-16,"Leda e il cigno (dipinto, elemento d'insieme) di Brusasorci Domenico (sec. XVI)",Leda e il cigno,[Leda e il cigno]
1973596,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500335083,Leda e il cigno (rilievo) - ambito veneto (sec. XVIII),Leda e il cigno,[Leda e il cigno]
688670,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900286615,Leda e il cigno (scultura) di Ammannati Bartolomeo (sec. XVI),Leda e il cigno,[Leda e il cigno]
1797632,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0300182819,"Leda e il cigno (disegno, opera isolata) di Cosway Richard (sec. XIX)",Leda e il cigno,[Leda e il cigno]
710424,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1100273575,Leda e il cigno (piatto) - bottega marchigiana (metà sec. XVI),Leda e il cigno,[Leda e il cigno]
175440,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0301934044,"Leda e il cigno (calco, opera isolata) - ambito italiano (prima metà sec. XIX)",Leda e il cigno,[Leda e il cigno]
1783012,https://w3id.org/arco/resource/HistoricOrArtisticProperty/2000044650,Leda e il cigno (rilievo) - bottega toscana (XIX),Leda e il cigno,[Leda e il cigno]
189538,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0800083598,Leda e il cigno (stampa smarginata) di Bonasone Giulio (sec. XVI),Leda e il cigno,[Leda e il cigno]
1119960,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1200865611,Leda e il cigno (rilievo) - manifattura italiana (seconda metà sec. XVIII),Leda e il cigno,[Leda e il cigno]
1609552,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1100002347,Leda e il cigno (acquamanile) - bottega marchigiana (sec. XVI),Leda e il cigno,[Leda e il cigno]
353828,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900281379-11,Leda e il cigno (rilievo) by Mati Piero (sec. XVI),Leda e il cigno,[Leda e il cigno]
1160640,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0800053633,"Leda e il cigno (gruppo scultoreo, opera isolata) - ambito bolognese (fine/inizio secc. XVIII/ XIX)",Leda e il cigno,[Leda e il cigno]
645706,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0300619865,"Leda e il cigno (stampa) - scuola italiana, scuola italiana (seconda metà sec. XVIII)",Leda e il cigno,[Leda e il cigno]
1032880,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500212299,Leda e il cigno (stampa smarginata) by Nicoletto da Modena (inizio sec. XVI),Leda e il cigno,[Leda e il cigno]
353840,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900281379-21,Leda e il cigno (rilievo) by Mati Piero (sec. XVI),Leda e il cigno,[Leda e il cigno]
324876,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500179382-8,"Leda e il cigno (dipinto, elemento d'insieme) - ambito veneto (sec. XVII)",Leda e il cigno,[Leda e il cigno]
1935090,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900451309,Leda e il cigno (statua) - produzione toscana (sec. XIX),Leda e il cigno,[Leda e il cigno]
1034466,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500212660,"Leda e il cigno (stampa smarginata) di Beatrizet Nicolas, Buonarroti Michelangelo (sec. XVI)",Leda e il cigno,[Leda e il cigno]
1119942,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1200865602,Leda e il cigno (scultura) by Cavaceppi Bartolomeo (seconda metà sec. XVIII),Leda e il cigno,[Leda e il cigno]
740762,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1500625989,Leda e il cigno (dipinto) by Giordano Luca (sec. XVII),Leda e il cigno,[Leda e il cigno]
1797630,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0300182818,"Leda e il cigno (disegno, opera isolata) di Cosway Richard (sec. XIX)",Leda e il cigno,[Leda e il cigno]
1141112,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1700033069,Leda e il cigno (dipinto) by Giordano Luca (scuola) (fine/inizio secc. XVII/ XVIII),Leda e il cigno,[Leda e il cigno]
190520,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0800084451,Leda e il cigno (stampa smarginata) - ambito italiano (?) (sec. XVI),Leda e il cigno,[Leda e il cigno]
438404,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500080007-12_1,Leda e il cigno (dipinto) di Lasinio Basilio - ambito trevigiano (sec. XVIII),Leda e il cigno,[Leda e il cigno]
189512,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0800083583,Leda e il cigno (stampa smarginata) di Bonasone Giulio (sec. XVI),Leda e il cigno,[Leda e il cigno]
561028,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900254728,Leda e il cigno (statua) di Lazzerini Pietro (sec. XIX),Leda e il cigno,[Leda e il cigno]
431536,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0303267719-1_5,"Leda e il cigno (dipinto murale) by Bertani Giovanni Battista, Bertani Giovanni Battista (cerchia), Ghisoni Fermo detto Fermo da Caravaggio (attribuito) (terzo quarto sec. XVI)",Leda e il cigno,[Leda e il cigno]
699550,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900641856,allegoria dell'aria con Leda e il cigno (dipinto) by Giordano Luca (bottega) (sec. XVII),allegoria dell'aria con Leda e il cigno,[Leda e il cigno]
911420,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0800403720,Leda e il cigno (dipinto) by Fustini Giuseppe (sec. XIX),Leda e il cigno,[Leda e il cigno]
571172,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900643219,"Leda e il cigno (cammeo) - bottega italiana (fine/ inizio, prima metà secc. XVI/ XVII, sec. XVII)",Leda e il cigno,[Leda e il cigno]
1528766,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1200863251,"Leda e il cigno, nascita dei dioscuri, di Elena e di Clitennestra (dipinto, complesso decorativo) - ambito romano (sec. XVI)","Leda e il cigno, nascita dei dioscuri, di Elena e di Clitennestra","[Leda e il cigno, Clitennestra]"
187918,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0800057119,"Figure e cavalli da Rubens, il ratto delle figlie di Leucippo (stampa) di Tolman Ronald (sec. XX)","Figure e cavalli da Rubens, il ratto delle figlie di Leucippo",[Leucippo]
361038,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900383414-17,"episodio della vita di Leucotoe (stampa smarginata, serie) di Le Pautre Jean (seconda metà sec. XVII)",episodio della vita di Leucotoe,[Leucotoe]
852812,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1500343587,"ritratto di Samuel Liber (stampa) di Hickel Joseph, Mansfeld Johann Ernst (sec. XVIII)",ritratto di Samuel Liber,[Liber]
1007834,https://w3id.org/arco/resource/HistoricOrArtisticProperty/2000240795,ritratto di Libero Meledina (dipinto) by Spada Ettore (sec. XX),ritratto di Libero Meledina,[Libero]
942284,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900476306,"Libero arbitrio (stampa, elemento d'insieme) - ambito veneto (sec. XVII, sec. XVII, sec. XVII)",Libero arbitrio,[Libero]
547904,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500676338,veduta del Canal Grande e statua d'Italia turrita come Libertas (manifesto) di Wolf Ferrari Teodoro (sec. XX),veduta del Canal Grande e statua d'Italia turrita come Libertas,[Libertas]
302746,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0300202831A-4,"Sibilla Libia (dipinto, elemento d'insieme) di Stella Fermo detto Fermo da Caravaggio (sec. XVI)",Sibilla Libia,[Libia]
460208,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0700043306A-9,"arrivo delle reliqiuie di San Siro in Libia (decorazione plastica, elemento d'insieme) di Carlone Giovanni Battista (attribuito) (metà sec. XVII)",arrivo delle reliqiuie di San Siro in Libia,[Libia]
663772,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500656818,una famiglia di coloni italiani attende davanti alla casa colonica n. 471 civico 56 dell'Ente Colonizzazione della Libia a Villaggio D'Annunzio nella provincia di Bengasi (manifesto) di Mossa Giovanni Maria - ambito italiano (sec. XX),una famiglia di coloni italiani attende davanti alla casa colonica n. 471 civico 56 dell'Ente Colonizzazione della Libia a Villaggio D'Annunzio nella provincia di Bengasi,[Libia]
776088,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500666296,sagoma della Libia su sfondo di bandiere nere (manifesto) by Romerani - ambito italiano (sec. XX),sagoma della Libia su sfondo di bandiere nere,[Libia]
1609528,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1100002335,morte di Licaone (acquamanile) - bottega marchigiana (sec. XVI),morte di Licaone,[Licaone]
361046,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900383414-5,"Licaone trasformato da Giove in volpe (stampa smarginata, serie) by Le Pautre Jean (seconda metà sec. XVII)",Licaone trasformato da Giove in volpe,"[Licaone, Giove]"
290020,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0100211037-12,"uccisione di Licurgo (decorazione pittorica, elemento d'insieme) di Casella Andrea (e aiuti), Casella Giacomo (e aiuti) (sec. XVII)",uccisione di Licurgo,[Licurgo]
191346,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0800198991,"Bacco, Ermete Trismegisto e il re Licurgo (Licurgo guarito su intercessione del popolo), Licurgo guarito su intercessione del popolo (dipinto) di Boulanger Jean (sec. XVII)",Licurgo guarito su intercessione del popolo,[Licurgo]
290024,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0100211037-2,"Licurgo recide le viti sacre a Bacco (decorazione pittorica, elemento d'insieme) di Casella Andrea (e aiuti), Casella Giacomo (e aiuti) (sec. XVII)",Licurgo recide le viti sacre a Bacco,"[Licurgo, Bacco]"
1609260,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900624230,Licurgo assale il Tiaso di Bacco (cratere) - ambito romano (sec. I),Licurgo assale il Tiaso di Bacco,"[Licurgo, Bacco]"
290032,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0100211037-6,"Licurgo uccide il figlio Driante (decorazione pittorica, elemento d'insieme) by Casella Andrea (e aiuti), Casella Giacomo (e aiuti) (sec. XVII)",Licurgo uccide il figlio Driante,"[Licurgo, Driante]"
360954,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900383033-5,"Licurgo e Numa Pompilio danno le leggi ai romani (stampa smarginata, serie) by Polidoro da Caravaggio, Galestruzzi Giovanni Battista (terzo quarto sec. XVII)",Licurgo e Numa Pompilio danno le leggi ai romani,"[Licurgo, Numa]"
815288,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1100139854,Licurgo e Numa Pompilio consegnano le leggi al popolo romano (disegno) by Zuccari Taddeo (attribuito) (sec. XVI),Licurgo e Numa Pompilio consegnano le leggi al popolo romano,"[Licurgo, Numa]"
1102896,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1100143210,Lido piceno (stampa) di De Carolis Adolfo (inizio sec. XX),Lido piceno,[Lido]
773760,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500658472,tuffatori sullo sfondo della piscina Lido di Bolzano (manifesto) di Sicher (sec. XX),tuffatori sullo sfondo della piscina Lido di Bolzano,[Lido]
773866,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500659075,"lanterna tra gondole, pali di legno e palina con il Lido di Venezia sullo sfondo (manifesto) - ambito italiano (sec. XX)","lanterna tra gondole, pali di legno e palina con il Lido di Venezia sullo sfondo",[Lido]
545158,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500656993,palione in laguna per l'attracco delle gondole di fronte ad un palazzo; sullo sfondo il Lido e l'isola di Pellestrina (manifesto) by Grassi Vittorio (sec. XX),palione in laguna per l'attracco delle gondole di fronte ad un palazzo; sullo sfondo il Lido e l'isola di Pellestrina,[Lido]
767320,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500439841,incendio al castello di San Nicoletto del Lido di Venezia (medaglia) - ambito veneziano (sec. XVIII),incendio al castello di San Nicoletto del Lido di Venezia,[Lido]
547152,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500672140,veduta di Lido di Venezia e particolare del portico di Palazzo Ducale in primo piano (manifesto) di Borgoni Mario (sec. XX),veduta di Lido di Venezia e particolare del portico di Palazzo Ducale in primo piano,[Lido]
761222,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500191391,"parata a S. Nicolò di Lido il giorno dell'Ascensione (stampa, elemento d'insieme) by Brustolon Giovanni Battista (attribuito), Canal Antonio detto Canaletto (attribuito) (terzo quarto sec. XVIII)",parata a S. Nicolò di Lido il giorno dell'Ascensione,[Lido]
767322,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500439842,incendio al castello di San Nicoletto del Lido di Venezia (medaglia) - ambito veneziano (sec. XVIII),incendio al castello di San Nicoletto del Lido di Venezia,[Lido]
777288,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500668589,vista notturna sul Lido di Venezia da Piazza san Marco (manifesto) - ambito italiano (sec. XX),vista notturna sul Lido di Venezia da Piazza san Marco,[Lido]
777326,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500668611,porticato di Palazzo Ducale con il rilievo del Peccato originale e veduta del Lido di Venezia (manifesto) di Borgoni Mario (inizio sec. XX),porticato di Palazzo Ducale con il rilievo del Peccato originale e veduta del Lido di Venezia,[Lido]
779884,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500675583,veduta del lungo mare Guglialmo Marconi del Lido di Venezia con numerosi spiaggianti e turisti; sulla destra il prestigioso Hotel Excelsior Palace (manifesto) di Ximenes Elio Ettore (sec. XX),veduta del lungo mare Guglialmo Marconi del Lido di Venezia con numerosi spiaggianti e turisti; sulla destra il prestigioso Hotel Excelsior Palace,[Lido]
2071418,https://w3id.org/arco/resource/Veneto/HistoricOrArtisticProperty/CRV-OA_0002449,Santa Rosa da Lima (DIPINTO) - scuola veneta (XVII),Santa Rosa da Lima,[Lima]
1901100,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1500660134,Madonna del Rosario con San Domenico e Santa Rosa da Lima (dipinto) - ambito Italia meridionale (prima metà sec. XIX),Madonna del Rosario con San Domenico e Santa Rosa da Lima,[Lima]
1596896,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0800274156,Madonna del Rosario con San Domenico e Santa Rosa da Lima (dipinto) - ambito tosco-emiliano (sec. XVIII),Madonna del Rosario con San Domenico e Santa Rosa da Lima,[Lima]
2003304,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900720674,Santa Rosa da Lima morente (scultura) by Lucchesi Urbano (seconda metà sec. XIX),Santa Rosa da Lima morente,[Lima]
2179742,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1800011506,"Santa Rosa da Lima (dipinto, opera isolata) - ambito calabrese (sec. XVIII)",Santa Rosa da Lima,[Lima]
2035328,https://w3id.org/arco/resource/HistoricOrArtisticProperty/1500192040-0,Madonna del Rosario con San Domenico e Santa Rosa da Lima (gruppo scultoreo) di Benaglia Paolo (sec. XVIII),Madonna del Rosario con San Domenico e Santa Rosa da Lima,[Lima]
2103490,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0800069696,Santa Rosa da Lima (dipinto) - ambito emiliano-romagnolo (sec. XIX),Santa Rosa da Lima,[Lima]
414478,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0100141621-1,"Santa Rosa da Lima (decorazione plastica, elemento d'insieme) - bottega lombarda (fine/inizio secc. XVII/ XVIII)",Santa Rosa da Lima,[Lima]
413990,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0100139068-1,Santa Rosa da Lima (dipinto) di Toso Lorenzo (secondo quarto sec. XIX),Santa Rosa da Lima,[Lima]
1483088,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900214267,Santa Rosa da Lima (dipinto) - ambito fiorentino (fine sec. XVII),Santa Rosa da Lima,[Lima]