In [207]:
from SPARQLWrapper import SPARQLWrapper, JSON
import pandas as pd

In [ ]:
#richiamo l'endpoint di wikidata 
wikidata_endpoint = "https://query.wikidata.org/sparql"
sparql_wd = SPARQLWrapper(wikidata_endpoint)

In [209]:
#creiamo una funzione per eseguire le query e restituire i risultati in un dataframe

def execute_wikidata_query(query, category):
    sparql_wd.setQuery(query)
    sparql_wd.setReturnFormat(JSON)
    results = sparql_wd.query().convert()
    
    #estraggo i risultati e li metto in un dataframe
    data = []
    for r in results["results"]["bindings"]: #per ogni risultato estraggo i valori dei campi
        entity = r["personaggio"]["value"] if "personaggio" in r else r["evento"]["value"] #se c'è il campo personaggio prendo quello, altrimenti prendo evento

        label = r["persLabel"]["value"] if "persLabel" in r else r["eventLabel"]["value"] #se c'è il campo persLabel prendo quello, altrimenti prendo eventLabel

        aliases = r["aliases"]["value"] if "aliases" in r else None #se c'è il campo aliases prendo quello, altrimenti metto None

        description = r["descrizione"]["value"] if "descrizione" in r else None #se c'è il campo descrizione prendo quello, altrimenti metto None
    
        data.append({
            "entity": entity,
            "label": label,
            "aliases": aliases,
            "description": description,
            "category": category
        })

    df = pd.DataFrame(
        data, 
        columns=["entity", "label", "aliases", "description", "category"]
    )

    return df

In [210]:
# QUERY PER GREEK DEITIES (743)
query_greek_deities = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q22989102
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""

#DF GREEK DEITIES
df_greek_deities = execute_wikidata_query(query_greek_deities, "greek_deity") 

print(len(df_greek_deities))

744

In [211]:
#df_greek_deities

In [212]:
#QUERY PER ROMAN DEITIES (193)

query_roman_deities = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q11688446
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""

#DF ROMAN DEITIES
df_roman_deities = execute_wikidata_query(query_roman_deities, "roman_deity")
print(len(df_roman_deities))

193

In [213]:
#df_roman_deities

In [214]:
#QUERY PER GREEK MYTHOLOGICAL CHARACTERS (4907) 

query_greek_mythological_characters = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q22988604
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""

#DF GREEK MYTHOLOGICAL CHARACTERS
df_greek_mythological_characters = execute_wikidata_query(query_greek_mythological_characters, "greek_mythological_character")
print(len(df_greek_mythological_characters))

4907

In [215]:
#df_greek_mythological_characters

In [216]:
#QUERY PER ROMAN MYTHOLOGICAL CHARACTERS (314)
query_roman_mythological_characters = """

SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q124940323
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""
#DF ROMAN MYTHOLOGICAL CHARACTERS
df_roman_mythological_characters = execute_wikidata_query(query_roman_mythological_characters, "roman_mythological_character")
print(len(df_roman_mythological_characters))

314

In [217]:
#df_roman_mythological_characters

In [218]:
#QUERY PER GROUP OF DEITIES (11 --> 7)
query_group_of_deities = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q111252729
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

  FILTER(
    BOUND(?descrizione) &&
    REGEX(LCASE(?descrizione), "greek|roman|greca|romana")
  )

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""

#DF GROUP OF DEITIES
df_group_of_deities = execute_wikidata_query(query_group_of_deities, "group_of_deities")
print(len(df_group_of_deities))

7

In [219]:
#df_group_of_deities
#i risultati vanno puliti

In [222]:
#QUERY PER SPIRIT OF NATURE (580 --> 450)

query_spirits_of_nature = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q11879837
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  FILTER NOT EXISTS {
    ?personaggio wdt:P31 ?excluded .
    VALUES ?excluded {
      wd:Q30168533
      wd:Q15711870
      wd:Q15632617
      wd:Q15773347
      wd:Q1114461
      wd:Q87576284
      wd:Q80447738
    }
  }

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

  FILTER(
    !BOUND(?descrizione) ||
    REGEX(LCASE(?descrizione), "grec|roman")
  )

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""
df_spirits_of_nature = execute_wikidata_query(query_spirits_of_nature, "spirits_of_nature")
print(len(df_spirits_of_nature))

450

In [223]:
#df_spirits_of_nature

In [224]:
#QUERY PER MYTHICAL WAR (12)

query_mythical_war = """
SELECT ?evento ?eventLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q24336068
    wd:Q63143903
  }

  VALUES ?mitiAmmessi {
    wd:Q34726
    wd:Q122173
  }

  ?evento wdt:P31/wdt:P279* ?classiAmmesse ;
          wdt:P361 ?mitiAmmessi .

  ?evento rdfs:label ?eventLabel .
  FILTER(LANG(?eventLabel) = "it")

  OPTIONAL {
    ?evento skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?evento schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?evento ?eventLabel ?descrizione
ORDER BY ?eventLabel
"""
df_mythical_war = execute_wikidata_query(query_mythical_war, "mythical_war")
print(len(df_mythical_war))

12

In [225]:
#df_mythical_war

In [229]:
#QUERY PER MYTICAL ENTITIES/ENTITY/GROUP OF MYTHICAL CREATURES (245)

query_mythical_entities = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q24334685
    wd:Q33294038
    wd:Q24337101
  }

  VALUES ?mitiAmmessi {
    wd:Q34726
    wd:Q122173
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse ;
              wdt:P361 ?mitiAmmessi .

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""
df_mythical_entities = execute_wikidata_query(query_mythical_entities, "mythical_entity")
print(len(df_mythical_entities))

245

In [ ]:
#df_mythical_entities

In [230]:
#QUERY PER IBRIDO con filtro (93 --> 72)
query_ibrido = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q20902363
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  FILTER NOT EXISTS {
    ?personaggio wdt:P31/wdt:P279* ?excludedClass .
    VALUES ?excludedClass {
      wd:Q30168533
      wd:Q15711870
      wd:Q15632617
      wd:Q15773347
      wd:Q1114461
      wd:Q87576284
      wd:Q80447738
    }
  }

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""
df_ibrido = execute_wikidata_query(query_ibrido, "ibrido")
df_ibrido = df_ibrido[df_ibrido["label"] != "Sirenetta"]  #ho tolto la sirenetta   
print(len(df_ibrido))

72

In [ ]:
#df_ibrido

In [231]:
#ORA CREIAMO UN UNICO DATAFRAME CON TUTTE LE CATEGORIE SENZA I DUPLICATI

df_uniti = pd.concat([
    df_greek_deities,
    df_roman_deities,
    df_greek_mythological_characters,
    df_roman_mythological_characters,
    df_group_of_deities,
    df_spirits_of_nature,
    df_mythical_war,
    df_mythical_entities,
    df_ibrido
], ignore_index=True)

len(df_uniti)
df_uniti.head(1)

,entity,label,aliases,description,category
0,http://www.wikidata.org/entity/Q304227,Aba,,ninfa naiade della mitologia greca,greek_deity

In [232]:
#elimino le entità duplicate
df_final = df_uniti.drop_duplicates(subset="entity")
len(df_final)

5390

In [ ]:
#df_final

In [ ]:
#df_final.sort_values("label")

In [242]:
#elimino i duplicati che non hanno la descrizione quando altri invece ce l'hanno

df_e = df_uniti.drop_duplicates(subset="entity").copy()

df_e["has_desc"] = df_e["description"].notna() & (df_e["description"].str.strip() != "")

def resolve_label(group):
    # CASO 1: almeno una descrizione → tengo solo quelle
    if group["has_desc"].any():
        return group[group["has_desc"]]

    # CASO 2: nessuna descrizione → tengo una sola riga
    return group.head(1)

df_finalissimo = (
    df_e.groupby("label", group_keys=False)
      .apply(resolve_label)
      .drop(columns=["has_desc"])
      .reset_index(drop=True)
)

C:\Users\annap\AppData\Local\Temp\ipykernel_42652\2521159014.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(resolve_label)

In [243]:
len(df_finalissimo)
#df_finalissimo.head(2)
#df_finalissimo

4868

In [244]:
#esporto il dataframe in un file csv
wikidata_csv = df_finalissimo.to_csv("wd_dataset.csv", index=False, sep=",", encoding="utf-8")

In [245]:
#estraggo tutte le label  
labels = (
    df_finalissimo["label"]
    .dropna() #tolgo i valori nulli
    .str.lower() #metto tutto in minuscolo
    .str.strip() #tolgo gli spazi bianchi all'inizio e alla fine
    .tolist() #converto in lista

)

#estraggo gli aliases separando quelli multipli
aliases = []
for alias_str in df_finalissimo["aliases"].dropna(): #per ogni stringa di alias che non è nulla
    alias_list = [alias.strip().lower() for alias in alias_str.split(",")] #separo gli alias con la virgola, tolgo gli spazi e metto tutto in minuscolo
    aliases.extend(alias_list) #aggiungo alla lista totale degli alias

#unisco tutto 
myth_terms = list(set(labels + aliases)) #unisco le label e gli alias, tolgo i duplicati con set e riconverto in lista
len(myth_terms)

4449

In [246]:
#ENDPOINT SPARLQ DI ARCO 
arco_endpoint = "https://dati.cultura.gov.it/sparql"

sparql_arco = SPARQLWrapper(arco_endpoint)
sparql_arco.setReturnFormat(JSON)

In [247]:
# NUMERO TOTALE DEI BENI STORICO ARTISTICI - senza duplicati 
query1 = """
PREFIX arco: <https://w3id.org/arco/ontology/arco/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT (COUNT(DISTINCT ?item) AS ?totalItems)
WHERE {
  ?item rdf:type <https://w3id.org/arco/ontology/arco/HistoricOrArtisticProperty> .
}
"""


sparql_arco.setQuery(query1)
results = sparql_arco.query().convert()

for result in results["results"]["bindings"]:
    print(f"Total Historic or Artistic Properties: {result['totalItems']['value']}")

Total Historic or Artistic Properties: 2258640

In [252]:
#query pr estrarre i dati dei beni storico artistici i batch da 20000  

query2 = f"""
PREFIX arco: <https://w3id.org/arco/ontology/arco/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX a-cd: <https://w3id.org/arco/ontology/context-description/>

SELECT DISTINCT ?item ?label ?title ?date ?description ?historical 
WHERE {{
  ?item rdf:type <https://w3id.org/arco/ontology/arco/HistoricOrArtisticProperty> .

  OPTIONAL {{ ?item rdfs:label ?label }}
  OPTIONAL {{ ?item dc:title ?title }}
  OPTIONAL {{ ?item dc:date ?date }}
  OPTIONAL {{ ?item dc:description ?description }}
  OPTIONAL {{ ?item a-cd:historicalInformation ?historical }}
}}

LIMIT 10000
OFFSET 0

"""

sparql_arco.setQuery(query2)
results = sparql_arco.query().convert()

In [253]:
rows = []

for r in results["results"]["bindings"]:

    rows.append({
        "item": r["item"]["value"] if "item" in r else None,
        "label": r["label"]["value"] if "label" in r else None,
        "title": r["title"]["value"] if "title" in r else None,
        "date": r["date"]["value"] if "date" in r else None,
        "description": r["description"]["value"] if "description" in r else None,
        #"historical": r["historical"]["value"] if "historical" in r else None
    })

df_arco = pd.DataFrame(rows)
len(df_arco)
#df_arco.head(10)

10000

In [254]:
# nel dataframe uniamo i campi di title e label in un unico campo "name" per facilitare la ricerca
df_arco["search_text"] = (
    df_arco["label"].fillna("") + " " + df_arco["title"].fillna("")
).str.lower()

df_arco[["label", "title", "search_text"]].head(1)

,label,title,search_text
0,"Arlecchino primordiale. Fine del cinquecento. Martinelli, figurino per costume di scena, maschile (disegno) by Fo, Dario (XX)","Arlecchino primordiale. Fine del cinquecento. Martinelli, figurino per costume di scena, maschile (disegno)","arlecchino primordiale. fine del cinquecento. martinelli, figurino per costume di scena, maschile (disegno) by fo, dario (xx) arlecchino primordiale. fine del cinquecento. martinelli, figurino per costume di scena, maschile (disegno)"

In [255]:
# Creiamo search_text solo da label e title
df_arco["search_text"] = (
    df_arco["label"].fillna("") + " " +
    df_arco["title"].fillna("")
).str.lower()

import re

# Funzione per trovare tutti i termini che matchano ESATTAMENTE
def find_matched_terms(text, terms_list):
    """Cerca tutti i termini che compaiono nel testo come parole esatte"""
    matched = []
    for term in terms_list:
        # Usa word boundaries \b per cercare la parola esatta
        if re.search(r'\b' + re.escape(term) + r'\b', text):
            matched.append(term)
    return ", ".join(matched) if matched else None

# Applica il matching
df_arco["matched_term"] = df_arco["search_text"].apply(
    lambda text: find_matched_terms(text, myth_terms)
)

# Filtra solo le righe con almeno un match
df_matches = df_arco[df_arco["matched_term"].notna()].copy()
print(f"Righe con almeno 1 match: {len(df_matches)}")

KeyboardInterrupt:

In [ ]:
# Verifica i risultati
print(f"Totale beni Arco: {len(df_arco)}")
print(f"Beni con match mitologico: {len(df_matches)}")

Totale beni Arco: 20000
Beni con match mitologico: 20000
Percentuale: 100.00%

In [ ]:
#vediamo i risultati
#df_matches.head(100)

,item,label,title,date,description,search_text,matched_term
0,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704280,"Arlecchino primordiale. Fine del cinquecento. Martinelli, figurino per costume di scena, maschile (disegno) by Fo, Dario (XX)","Arlecchino primordiale. Fine del cinquecento. Martinelli, figurino per costume di scena, maschile (disegno)",1985-1985,"Disegno a colori eseguito a penna, pennarello e pastello a cera raffigurante il primo Arlecchino: figurino maschile con cappello, maschera, costume a foglie colorate con cinturino e borsello. Note manoscritte","arlecchino primordiale. fine del cinquecento. martinelli, figurino per costume di scena, maschile (disegno) by fo, dario (xx) arlecchino primordiale. fine del cinquecento. martinelli, figurino per costume di scena, maschile (disegno)",", ino, hile, dia, io"
1,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704280,"Arlecchino primordiale. Fine del cinquecento. Martinelli, figurino per costume di scena, maschile (disegno) di Fo, Dario (XX)","Arlecchino primordiale. Fine del cinquecento. Martinelli, figurino per costume di scena, maschile (disegno)",1985-1985,"Disegno a colori eseguito a penna, pennarello e pastello a cera raffigurante il primo Arlecchino: figurino maschile con cappello, maschera, costume a foglie colorate con cinturino e borsello. Note manoscritte","arlecchino primordiale. fine del cinquecento. martinelli, figurino per costume di scena, maschile (disegno) di fo, dario (xx) arlecchino primordiale. fine del cinquecento. martinelli, figurino per costume di scena, maschile (disegno)",", ino, hile, dia, io"
2,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704131,"Pulcinella, maschera della Commedia dell'Arte (maschera) di Sartori, Donato (XX)","Pulcinella, maschera della Commedia dell'Arte (maschera)",ca 1979-ante 1985,"Maschera modellata in cuoio, dipinto di bianco e patinato, su stampo in legno. Ai bordi della maschera, all'altezza degli occhi, ci sono due viti con un filo elastico che permette di calzarla sul viso","pulcinella, maschera della commedia dell'arte (maschera) di sartori, donato (xx) pulcinella, maschera della commedia dell'arte (maschera)",", ato, hera, dia, era"
3,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704131,"Pulcinella, maschera della Commedia dell'Arte (maschera) by Sartori, Donato (XX)","Pulcinella, maschera della Commedia dell'Arte (maschera)",ca 1979-ante 1985,"Maschera modellata in cuoio, dipinto di bianco e patinato, su stampo in legno. Ai bordi della maschera, all'altezza degli occhi, ci sono due viti con un filo elastico che permette di calzarla sul viso","pulcinella, maschera della commedia dell'arte (maschera) by sartori, donato (xx) pulcinella, maschera della commedia dell'arte (maschera)",", ato, hera, dia, era"
4,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704143,"Truffaldino, maschera della Commedia dell'Arte (maschera) di Sartori, Donato (XX)","Truffaldino, maschera della Commedia dell'Arte (maschera)",ca 1979-ante 1985,"Maschera modellata in cuoio patinato su stampo in legno. Sul lato sinistro della fronte è presente l'accenno di un corno rosso. Ai bordi della maschera, all’altezza degli occhi, ci sono due fori con un filo elastico che permette di calzarla sul viso","truffaldino, maschera della commedia dell'arte (maschera) di sartori, donato (xx) truffaldino, maschera della commedia dell'arte (maschera)",", ino, ato, hera, dia, era"
5,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704143,"Truffaldino, maschera della Commedia dell'Arte (maschera) by Sartori, Donato (XX)","Truffaldino, maschera della Commedia dell'Arte (maschera)",ca 1979-ante 1985,"Maschera modellata in cuoio patinato su stampo in legno. Sul lato sinistro della fronte è presente l'accenno di un corno rosso. Ai bordi della maschera, all’altezza degli occhi, ci sono due fori con un filo elastico che permette di calzarla sul viso","truffaldino, maschera della commedia dell'arte (maschera) by sartori, donato (xx) truffaldino, maschera della commedia dell'arte (maschera)",", ino, ato, hera, dia, era"
6,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704560,"studio per maschera d'oro (dei re del Gipango) (disegno) by Fo, Dario (XX)",disegno,1963-1963,Disegno eseguito a penna su foglio di carta bianca raffigurante lo studio della maschera d'oro dei re del Gipango,"studio per maschera d'oro (dei re del gipango) (disegno) by fo, dario (xx) disegno",", oro, hera, era, dio, io, pan"
7,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704560,"studio per maschera d'oro (dei re del Gipango) (disegno) di Fo, Dario (XX)",disegno,1963-1963,Disegno eseguito a penna su foglio di carta bianca raffigurante lo studio della maschera d'oro dei re del Gipango,"studio per maschera d'oro (dei re del gipango) (disegno) di fo, dario (xx) disegno",", oro, hera, era, dio, io, pan"
8,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704857,"Studio per Medea, figura femminile a mezzo busto (disegno) di Fo, Dario (XX)","Studio per Medea, figura femminile a mezzo busto (disegno)",1978-1978,"Disegno a colori eseguito con pastelli a cera su foglio di carta bianca. Studio di una figura femminile, raffigurata a mezzo busto, con le mani sul viso. Franca Rame interpreta Medea di Euripide. Figura variopinta contornata di nero su sfondo bianco","studio per medea, figura femminile a mezzo busto (disegno) di fo, dario (xx) studio per medea, figura femminile a mezzo busto (disegno)",", mini, ea, medea, dio, io"
9,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704857,"Studio per Medea, figura femminile a mezzo busto (disegno) by Fo, Dario (XX)","Studio per Medea, figura femminile a mezzo busto (disegno)",1978-1978,"Disegno a colori eseguito con pastelli a cera su foglio di carta bianca. Studio di una figura femminile, raffigurata a mezzo busto, con le mani sul viso. Franca Rame interpreta Medea di Euripide. Figura variopinta contornata di nero su sfondo bianco","studio per medea, figura femminile a mezzo busto (disegno) by fo, dario (xx) studio per medea, figura femminile a mezzo busto (disegno)",", mini, ea, medea, dio, io"
10,https://w3id.org/arco/resource/Lombardia/HistoricOrArtisticProperty/0302126313,Grappolo d'uva (tazzina da caffè) by Ceramiche Pareschi (ultimo quarto sec. XX),tazzina da caffè,post 1975-ante 1999,"Tazzina da caffè con corpo leggermente svasato; manico a ""C"" schiacciato; fondo bianco decorato con grappolo d'uva; bordo rifinito in verde.",grappolo d'uva (tazzina da caffè) by ceramiche pareschi (ultimo quarto sec. xx) tazzina da caffè,", ares, era"
11,https://w3id.org/arco/resource/Lombardia/HistoricOrArtisticProperty/0302126313,Grappolo d'uva (tazzina da caffè) di Ceramiche Pareschi (ultimo quarto sec. XX),tazzina da caffè,post 1975-ante 1999,"Tazzina da caffè con corpo leggermente svasato; manico a ""C"" schiacciato; fondo bianco decorato con grappolo d'uva; bordo rifinito in verde.",grappolo d'uva (tazzina da caffè) di ceramiche pareschi (ultimo quarto sec. xx) tazzina da caffè,", ares, era"
12,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704652,"uomo seduto con tavola, arcangelo e figure maschili, studio per manifesto (disegno) by Fo, Dario (XX)",disegno (bozzetto),1964-1964,"Disegno eseguito a inchiostro su carta bianca incollata su cartoncino. Da destra, figura maschile in abito borghese con bombetta e cravatta a farfalla, dall'aspetto severo, seduta in una sedia con una tavola di pietra in mano (leggi di Mosè); sulla sinistra in basso, schizzo di due figure maschili in scala ridotta; al centro, figura maschile con costume a losanghe (Arlecchino); in alto, figura maschile alata (arcangelo) in posizione orizzontale","uomo seduto con tavola, arcangelo e figure maschili, studio per manifesto (disegno) by fo, dario (xx) disegno (bozzetto)",", angelo, dio, festo, io"
13,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704652,"uomo seduto con tavola, arcangelo e figure maschili, studio per manifesto (disegno) di Fo, Dario (XX)",disegno (bozzetto),1964-1964,"Disegno eseguito a inchiostro su carta bianca incollata su cartoncino. Da destra, figura maschile in abito borghese con bombetta e cravatta a farfalla, dall'aspetto severo, seduta in una sedia con una tavola di pietra in mano (leggi di Mosè); sulla sinistra in basso, schizzo di due figure maschili in scala ridotta; al centro, figura maschile con costume a losanghe (Arlecchino); in alto, figura maschile alata (arcangelo) in posizione orizzontale","uomo seduto con tavola, arcangelo e figure maschili, studio per manifesto (disegno) di fo, dario (xx) disegno (bozzetto)",", angelo, dio, festo, io"
14,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704575,"Regina Isabella, figurino per costume si scena, femminile, in stile cinquecentesco (disegno) by Fo, Dario, Carbonell, Miguel (XX)","Regina Isabella, figurino per costume si scena, femminile, in stile cinquecentesco (disegno)",1992-1992,"Disegno eseguito a pennarello su foglio di carta bianca incollato su cartoncino blu. Figurino per costume di scena, femminile: regina Isabella","regina isabella, figurino per costume si scena, femminile, in stile cinquecentesco (disegno) by fo, dario, carbonell, miguel (xx) regina isabella, figurino per costume si scena, femminile, in stile cinquecentesco (disegno)",", car, mini, ino, io, egina"
15,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704575,"Regina Isabella, figurino per costume si scena, femminile, in stile cinquecentesco (disegno) di Fo, Dario, Carbonell, Miguel (XX)","Regina Isabella, figurino per costume si scena, femminile, in stile cinquecentesco (disegno)",1992-1992,"Disegno eseguito a pennarello su foglio di carta bianca incollato su cartoncino blu. Figurino per costume di scena, femminile: regina Isabella","regina isabella, figurino per costume si scena, femminile, in stile cinquecentesco (disegno) di fo, dario, carbonell, miguel (xx) regina isabella, figurino per costume si scena, femminile, in stile cinquecentesco (disegno)",", car, mini, ino, io, egina"
16,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704163,"Arlecchino primordiale, figurino per costume di scena, maschile (disegno) by Fo, Dario (XX)","Arlecchino primordiale, figurino per costume di scena, maschile (disegno)",1985-1985,"Fotocopia in rosso ritoccata a mano con pennarello e pittura a tempera acquerellata raffigurante il primo Arlecchino: figurino maschile con cappello, maschera, costume a foglie dai colori accesi con cinturino e borsello o ""scarsèla"". Note manoscritte","arlecchino primordiale, figurino per costume di scena, maschile (disegno) by fo, dario (xx) arlecchino primordiale, figurino per costume di scena, maschile (disegno)",", ino, hile, dia, io"
17,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704163,"Arlecchino primordiale, figurino per costume di scena, maschile (disegno) di Fo, Dario (XX)","Arlecchino primordiale, figurino per costume di scena, maschile (disegno)",1985-1985,"Fotocopia in rosso ritoccata a mano con pennarello e pittura a tempera acquerellata raffigurante il primo Arlecchino: figurino maschile con cappello, maschera, costume a foglie dai colori accesi con cinturino e borsello o ""scarsèla"". Note manoscritte","arlecchino primordiale, figurino per costume di scena, maschile (disegno) di fo, dario (xx) arlecchino primordiale, figurino per costume di scena, maschile (disegno)",", ino, hile, dia, io"
18,https://w3id.org/arco/resource/Lombardia/HistoricOrArtisticProperty/0302021552,"Kappa su granchio, CREATURA FANTASTICA e ANIMALE (scultura) di Ikkosai Toun (metà sec. XIX)","Kappa su granchio, CREATURA FANTASTICA e ANIMALE (scultura)",ca 1840-ca 1860,"Questo netsuke raffigura un granchio (kani) sul quale sta posato un kappa, la cui zampa anteriore sinistra è trattenuta dalla chela destra del mollusco. I due fori dell'himotoshi sono ubicati sul lato inferiore della composizione.","kappa su granchio, creatura fantastica e animale (scultura) di ikkosai toun (metà sec. xix) kappa su granchio, creatura fantastica e animale (scultura)",", anchio, rea, ica, ea, chio, anta, io"
19,https://w3id.org/arco/resource/Lombardia/HistoricOrArtisticProperty/0302021552,"Kappa su granchio, CREATURA FANTASTICA e ANIMALE (scultura) by Ikkosai Toun (metà sec. XIX)","Kappa su granchio, CREATURA FANTASTICA e ANIMALE (scultura)",ca 1840-ca 1860,"Questo netsuke raffigura un granchio (kani) sul quale sta posato un kappa, la cui zampa anteriore sinistra è trattenuta dalla chela destra del mollusco. I due fori dell'himotoshi sono ubicati sul lato inferiore della composizione.","kappa su granchio, creatura fantastica e animale (scultura) by ikkosai toun (metà sec. xix) kappa su granchio, creatura fantastica e animale (scultura)",", anchio, rea, ica, ea, chio, anta, io"
20,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500705036,"Serenata, studio di figure per azione scenica (dipinto) by Fo, Dario (XX)","Serenata, studio di figure per azione scenica (dipinto)",1987-1987,"Dipinto a colori eseguito con inchiostro e pittura a tempera acquerellata su foglio di carta bianca. Studio di figure per azione scenica: al centro, due figure umane, di cui una con chitarra in mano, ballano agitando le braccia; a sinistra, maschera della luna; a destra, un telo bianco e un asino che scalcia. Figure variopinte su piano ocra e sfondo blu","serenata, studio di figure per azione scenica (dipinto) by fo, dario (xx) serenata, studio di figure per azione scenica (dipinto)",", rena, ica, dio, io, ione"
21,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500705036,"Serenata, studio di figure per azione scenica (dipinto) di Fo, Dario (XX)","Serenata, studio di figure per azione scenica (dipinto)",1987-1987,"Dipinto a colori eseguito con inchiostro e pittura a tempera acquerellata su foglio di carta bianca. Studio di figure per azione scenica: al centro, due figure umane, di cui una con chitarra in mano, ballano agitando le braccia; a sinistra, maschera della luna; a destra, un telo bianco e un asino che scalcia. Figure variopinte su piano ocra e sfondo blu","serenata, studio di figure per azione scenica (dipinto) di fo, dario (xx) serenata, studio di figure per azione scenica (dipinto)",", rena, ica, dio, io, ione"
22,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704365,"Gag del fiore magico da annusare, appunti con schizzi e note manoscritte (disegno) di Fo, Dario, Fo, Dario (XX)","Gag del fiore magico da annusare, appunti con schizzi e note manoscritte (disegno)",1985-1985,"Fotocopia in rosso ritoccata a mano con pastelli a cera colorati. Studio su canovacci per Arlecchino. Appunti per lo svolgimento dell'azione scenica: ""gag fiore magico da annusare"". Figura femminile e figura maschile che le porge il fiore","gag del fiore magico da annusare, appunti con schizzi e note manoscritte (disegno) di fo, dario, fo, dario (xx) gag del fiore magico da annusare, appunti con schizzi e note manoscritte (disegno)",", ore, io"
23,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704365,"Gag del fiore magico da annusare, appunti con schizzi e note manoscritte (disegno) by Fo, Dario, Fo, Dario (XX)","Gag del fiore magico da annusare, appunti con schizzi e note manoscritte (disegno)",1985-1985,"Fotocopia in rosso ritoccata a mano con pastelli a cera colorati. Studio su canovacci per Arlecchino. Appunti per lo svolgimento dell'azione scenica: ""gag fiore magico da annusare"". Figura femminile e figura maschile che le porge il fiore","gag del fiore magico da annusare, appunti con schizzi e note manoscritte (disegno) by fo, dario, fo, dario (xx) gag del fiore magico da annusare, appunti con schizzi e note manoscritte (disegno)",", ore, io"
24,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704138,"volto maschile (maschera) by Fo, Jacopo (XX)",maschera,ca 1980-ca 1981,"Maschera modellata in cartapesta. Volto dipinto di nero con decorazioni pittoriche in colore bianco e oro. Sul lato destro della fronte è presente l’accenno di un corno. Ai bordi della maschera, all'altezza degli occhi, è fissato un filo elastico che permette di calzarla sul viso","volto maschile (maschera) by fo, jacopo (xx) maschera",", opo, hile, hera, era"
25,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704138,"volto maschile (maschera) di Fo, Jacopo (XX)",maschera,ca 1980-ca 1981,"Maschera modellata in cartapesta. Volto dipinto di nero con decorazioni pittoriche in colore bianco e oro. Sul lato destro della fronte è presente l’accenno di un corno. Ai bordi della maschera, all'altezza degli occhi, è fissato un filo elastico che permette di calzarla sul viso","volto maschile (maschera) di fo, jacopo (xx) maschera",", opo, hile, hera, era"
26,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704535,"figurino per costume di scena, maschile, in stile cinquecentesco (disegno) by Fo, Dario (XX)",disegno (bozzetto),1963-1963,"Disegno eseguito a pennarello su foglio di carta bianca. Figurino per costume di scena, maschile, composto da maglia, cintura e stivali","figurino per costume di scena, maschile, in stile cinquecentesco (disegno) by fo, dario (xx) disegno (bozzetto)",", ino, hile, io"
27,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704535,"figurino per costume di scena, maschile, in stile cinquecentesco (disegno) di Fo, Dario (XX)",disegno (bozzetto),1963-1963,"Disegno eseguito a pennarello su foglio di carta bianca. Figurino per costume di scena, maschile, composto da maglia, cintura e stivali","figurino per costume di scena, maschile, in stile cinquecentesco (disegno) di fo, dario (xx) disegno (bozzetto)",", ino, hile, io"
28,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704807,"grande pupazzo, figure umane con bastoni sopra un palcoscenico, studio per manifesto (disegno) by Fo, Dario (XX)",disegno (bozzetto),1970-1970,"Stampa in rosso di un manifesto con l'iscrizione NUOVA SCENA - 1970, raffigurante un grande pupazzo con le braccia aperte e sei figure maschili disposte sopra un praticabile a due livelli, ritoccata a mano con della pittura a tempera di colore rosso e nero","grande pupazzo, figure umane con bastoni sopra un palcoscenico, studio per manifesto (disegno) by fo, dario (xx) disegno (bozzetto)",", mane, dio, festo, io"
29,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704807,"grande pupazzo, figure umane con bastoni sopra un palcoscenico, studio per manifesto (disegno) di Fo, Dario (XX)",disegno (bozzetto),1970-1970,"Stampa in rosso di un manifesto con l'iscrizione NUOVA SCENA - 1970, raffigurante un grande pupazzo con le braccia aperte e sei figure maschili disposte sopra un praticabile a due livelli, ritoccata a mano con della pittura a tempera di colore rosso e nero","grande pupazzo, figure umane con bastoni sopra un palcoscenico, studio per manifesto (disegno) di fo, dario (xx) disegno (bozzetto)",", mane, dio, festo, io"
30,https://w3id.org/arco/resource/HistoricOrArtisticProperty/0500704611,"figurino per costume di scena, maschile, in stile cinquecentesco (disegno) di Fo, Dario, Carbonell, Miguel (XX)",disegno (bozzetto),1992-1992,"Disegno eseguito a pennarello su foglio di carta bianca incollato su cartoncino giallo. Figurino per costume di scena, maschile: secondo accusatore. In alto, fissati con dei punti metallici, ci sono campioni di stoffa per la realizzazione dell'abito. Figura variopinta su sfondo neutro","figurino per costume di scena, maschile, in stile cinquecentesco (disegno) di fo, dario, carbonell, miguel (xx) disegno (bozzetto)",", car, ino, hile, io"