In [111]:
from SPARQLWrapper import SPARQLWrapper, JSON
import pandas as pd

In [112]:
#richiamo l'endpoint di wikidata 
wikidata_endpoint = "https://query.wikidata.org/sparql"
sparql_wd = SPARQLWrapper(wikidata_endpoint)

In [113]:
#creiamo una funzione per eseguire le query e restituire i risultati in un dataframe

def execute_wikidata_query(query, category):
    sparql_wd.setQuery(query)
    sparql_wd.setReturnFormat(JSON)
    results = sparql_wd.query().convert()
    
    #estraggo i risultati e li metto in un dataframe
    data = []
    for r in results["results"]["bindings"]: #per ogni risultato estraggo i valori dei campi
        entity = r["personaggio"]["value"] if "personaggio" in r else r["evento"]["value"] #se c'è il campo personaggio prendo quello, altrimenti prendo evento

        label = r["persLabel"]["value"] if "persLabel" in r else r["eventLabel"]["value"] #se c'è il campo persLabel prendo quello, altrimenti prendo eventLabel

        aliases = r["aliases"]["value"] if "aliases" in r else None #se c'è il campo aliases prendo quello, altrimenti metto None

        description = r["descrizione"]["value"] if "descrizione" in r else None #se c'è il campo descrizione prendo quello, altrimenti metto None
    
        data.append({
            "entity": entity,
            "label": label,
            "aliases": aliases,
            "description": description,
            "category": category
        })

    df = pd.DataFrame(
        data, 
        columns=["entity", "label", "aliases", "description", "category"]
    )

    return df

In [114]:
# QUERY PER GREEK DEITIES (743)
query_greek_deities = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q22989102
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""

#DF GREEK DEITIES
df_greek_deities = execute_wikidata_query(query_greek_deities, "greek_deity") 

print(len(df_greek_deities))

744

In [115]:
#df_greek_deities

In [116]:
#QUERY PER ROMAN DEITIES (193)

query_roman_deities = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q11688446
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""

#DF ROMAN DEITIES
df_roman_deities = execute_wikidata_query(query_roman_deities, "roman_deity")
print(len(df_roman_deities))

193

In [117]:
#df_roman_deities

In [ ]:
#QUERY PER GREEK MYTHOLOGICAL CHARACTERS (4907) 

query_greek_mythological_characters = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q22988604
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""

#DF GREEK MYTHOLOGICAL CHARACTERS
df_greek_mythological_characters = execute_wikidata_query(query_greek_mythological_characters, "greek_mythological_character")
print(len(df_greek_mythological_characters))

4908

In [119]:
#df_greek_mythological_characters

In [120]:
#QUERY PER ROMAN MYTHOLOGICAL CHARACTERS (314)
query_roman_mythological_characters = """

SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q124940323
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""
#DF ROMAN MYTHOLOGICAL CHARACTERS
df_roman_mythological_characters = execute_wikidata_query(query_roman_mythological_characters, "roman_mythological_character")
print(len(df_roman_mythological_characters))

314

In [121]:
#df_roman_mythological_characters

In [122]:
#QUERY PER GROUP OF DEITIES (11 --> 7)
query_group_of_deities = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q111252729
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

  FILTER(
    BOUND(?descrizione) &&
    REGEX(LCASE(?descrizione), "greek|roman|greca|romana")
  )

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""

#DF GROUP OF DEITIES
df_group_of_deities = execute_wikidata_query(query_group_of_deities, "group_of_deities")
print(len(df_group_of_deities))

7

In [123]:
#df_group_of_deities
#i risultati vanno puliti

In [124]:
#QUERY PER SPIRIT OF NATURE (580 --> 450)

query_spirits_of_nature = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q11879837
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  FILTER NOT EXISTS {
    ?personaggio wdt:P31 ?excluded .
    VALUES ?excluded {
      wd:Q30168533
      wd:Q15711870
      wd:Q15632617
      wd:Q15773347
      wd:Q1114461
      wd:Q87576284
      wd:Q80447738
    }
  }

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

  FILTER(
    !BOUND(?descrizione) ||
    REGEX(LCASE(?descrizione), "grec|roman")
  )

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""
df_spirits_of_nature = execute_wikidata_query(query_spirits_of_nature, "spirits_of_nature")
print(len(df_spirits_of_nature))

450

In [125]:
#df_spirits_of_nature

In [126]:
#QUERY PER MYTHICAL WAR (12)

query_mythical_war = """
SELECT ?evento ?eventLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q24336068
    wd:Q63143903
  }

  VALUES ?mitiAmmessi {
    wd:Q34726
    wd:Q122173
  }

  ?evento wdt:P31/wdt:P279* ?classiAmmesse ;
          wdt:P361 ?mitiAmmessi .

  ?evento rdfs:label ?eventLabel .
  FILTER(LANG(?eventLabel) = "it")

  OPTIONAL {
    ?evento skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?evento schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?evento ?eventLabel ?descrizione
ORDER BY ?eventLabel
"""
df_mythical_war = execute_wikidata_query(query_mythical_war, "mythical_war")
print(len(df_mythical_war))

12

In [127]:
#df_mythical_war

In [129]:
#QUERY PER MYTICAL ENTITIES/ENTITY/GROUP OF MYTHICAL CREATURES (245)

query_mythical_entities = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q24334685
    wd:Q33294038
    wd:Q24337101
  }

  VALUES ?mitiAmmessi {
    wd:Q34726
    wd:Q122173
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse ;
              wdt:P361 ?mitiAmmessi .

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""
df_mythical_entities = execute_wikidata_query(query_mythical_entities, "mythical_entity")
print(len(df_mythical_entities))

245

In [155]:
df_mythical_entities

,entity,label,aliases,description,category
0,http://www.wikidata.org/entity/Q305570,Abaride,,Rutulo nella mitologia romana,mythical_entity
1,http://www.wikidata.org/entity/Q318682,Abellione,,None,mythical_entity
2,http://www.wikidata.org/entity/Q321399,Abii,,popolo presente nell'Iliade,mythical_entity
3,http://www.wikidata.org/entity/Q3603796,Abraxas,,None,mythical_entity
4,http://www.wikidata.org/entity/Q13081186,Acheronte,,fiume della mitologia greca,mythical_entity
...,...,...,...,...,...
240,http://www.wikidata.org/entity/Q2419033,teomachia,,None,mythical_entity
241,http://www.wikidata.org/entity/Q20644862,tridente di Poseidone,"triaina, tridente",attributo di Poseidone nella mitologia greca,mythical_entity
242,http://www.wikidata.org/entity/Q937164,vaso di Pandora,,oggetto della mitologia greca,mythical_entity
243,http://www.wikidata.org/entity/Q212262,vello d'oro,,oggetto mitologico greco antico,mythical_entity
244,http://www.wikidata.org/entity/Q1857362,volpe di Teumesso,,volpe della mitologia greca,mythical_entity

In [131]:
#QUERY PER IBRIDO con filtro (93 --> 72)
query_ibrido = """
SELECT ?personaggio ?persLabel
       (GROUP_CONCAT(DISTINCT ?aka; separator=", ") AS ?aliases)
       ?descrizione

WHERE {

  VALUES ?classiAmmesse {
    wd:Q20902363
  }

  ?personaggio wdt:P31/wdt:P279* ?classiAmmesse .

  FILTER NOT EXISTS {
    ?personaggio wdt:P31/wdt:P279* ?excludedClass .
    VALUES ?excludedClass {
      wd:Q30168533
      wd:Q15711870
      wd:Q15632617
      wd:Q15773347
      wd:Q1114461
      wd:Q87576284
      wd:Q80447738
    }
  }

  ?personaggio rdfs:label ?persLabel .
  FILTER(LANG(?persLabel) = "it")

  OPTIONAL {
    ?personaggio skos:altLabel ?aka .
    FILTER(LANG(?aka) = "it")
  }

  OPTIONAL {
    ?personaggio schema:description ?descrizione .
    FILTER(LANG(?descrizione) = "it")
  }

}

GROUP BY ?personaggio ?persLabel ?descrizione
ORDER BY ?persLabel
"""
df_ibrido = execute_wikidata_query(query_ibrido, "ibrido")
df_ibrido = df_ibrido[df_ibrido["label"] != "Sirenetta"]  #ho tolto la sirenetta   
print(len(df_ibrido))

72

In [154]:
df_ibrido

,entity,label,aliases,description,category
0,http://www.wikidata.org/entity/Q305611,Abante,,"centauro della mitologia greca, figlio di Issione",ibrido
1,http://www.wikidata.org/entity/Q21547793,Acoloe,,arpia della mitologia greca,ibrido
2,http://www.wikidata.org/entity/Q3605939,Aellopoda,,arpia della mitologia greca,ibrido
3,http://www.wikidata.org/entity/Q26806435,Afareo,,centauro della mitologia greca,ibrido
4,http://www.wikidata.org/entity/Q28045772,Afeida,,centauro della mitologia greca,ibrido
...,...,...,...,...,...
67,http://www.wikidata.org/entity/Q464091,Sileno,Papposileno,personaggio della mitologia greca,ibrido
69,http://www.wikidata.org/entity/Q125377972,Stifelo,,None,ibrido
70,http://www.wikidata.org/entity/Q126923833,Taumante,,None,ibrido
71,http://www.wikidata.org/entity/Q124901905,Teleboa,,None,ibrido
72,http://www.wikidata.org/entity/Q16680068,Tereo,,centauro della mitologia greca,ibrido

In [133]:
#ORA CREIAMO UN UNICO DATAFRAME CON TUTTE LE CATEGORIE SENZA I DUPLICATI

df_uniti = pd.concat([
    df_greek_deities,
    df_roman_deities,
    df_greek_mythological_characters,
    df_roman_mythological_characters,
    df_group_of_deities,
    df_spirits_of_nature,
    df_mythical_war,
    df_mythical_entities,
    df_ibrido
], ignore_index=True)

len(df_uniti)
df_uniti.head(1)

,entity,label,aliases,description,category
0,http://www.wikidata.org/entity/Q304227,Aba,,ninfa naiade della mitologia greca,greek_deity

In [134]:
#elimino le entità duplicate
df_final = df_uniti.drop_duplicates(subset="entity")
len(df_final)

5390

In [153]:
#df_final

In [136]:
#df_final.sort_values("label")

In [137]:
#elimino i duplicati che non hanno la descrizione quando altri invece ce l'hanno

df_e = df_uniti.drop_duplicates(subset="entity").copy()

df_e["has_desc"] = df_e["description"].notna() & (df_e["description"].str.strip() != "")

def resolve_label(group):
    # CASO 1: almeno una descrizione → tengo solo quelle
    if group["has_desc"].any():
        return group[group["has_desc"]]

    # CASO 2: nessuna descrizione → tengo una sola riga
    return group.head(1)

df_finalissimo = (
    df_e.groupby("label", group_keys=False)
      .apply(resolve_label)
      .drop(columns=["has_desc"])
      .reset_index(drop=True)
)

C:\Users\annap\AppData\Local\Temp\ipykernel_4564\2521159014.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(resolve_label)

In [ ]:
len(df_finalissimo)
#df_finalissimo.head(2)
#df_finalissimo

,entity,label,aliases,description,category
0,http://www.wikidata.org/entity/Q304227,Aba,,ninfa naiade della mitologia greca,greek_deity
1,http://www.wikidata.org/entity/Q305607,Abante,Abantiade,"re di Argo nella mitologia greca, figlio di Li...",greek_mythological_character
2,http://www.wikidata.org/entity/Q305604,Abante,,"personaggio della mitologia greca, amico di Pe...",greek_mythological_character
3,http://www.wikidata.org/entity/Q305611,Abante,,"centauro della mitologia greca, figlio di Issione",greek_mythological_character
4,http://www.wikidata.org/entity/Q305609,Abante,,"personaggio della mitologia greca, figlio di E...",greek_mythological_character
...,...,...,...,...,...
4863,http://www.wikidata.org/entity/Q20644862,tridente di Poseidone,"triaina, tridente",attributo di Poseidone nella mitologia greca,mythical_entity
4864,http://www.wikidata.org/entity/Q937164,vaso di Pandora,,oggetto della mitologia greca,mythical_entity
4865,http://www.wikidata.org/entity/Q212262,vello d'oro,,oggetto mitologico greco antico,mythical_entity
4866,http://www.wikidata.org/entity/Q1857362,volpe di Teumesso,,volpe della mitologia greca,mythical_entity
4867,http://www.wikidata.org/entity/Q942519,Śuri,"Šuri, Soranus, Suri",divinità etrusca,roman_deity

In [139]:
#esporto il dataframe in un file csv
wikidata_csv = df_finalissimo.to_csv("wd_dataset.csv", index=False, sep=",", encoding="utf-8")

In [140]:
#estraggo tutte le label  
labels = (
    df_finalissimo["label"]
    .dropna() #tolgo i valori nulli
    .str.strip() #tolgo gli spazi bianchi all'inizio e alla fine
    .tolist() #converto in lista

)

#estraggo gli aliases separando quelli multipli
aliases = []
for alias_str in df_finalissimo["aliases"].dropna(): #per ogni stringa di alias che non è nulla
    alias_list = [alias.strip() for alias in alias_str.split(",")] #separo gli alias con la virgola, tolgo gli spazi e metto tutto in minuscolo
    aliases.extend(alias_list) #aggiungo alla lista totale degli alias

#unisco tutto 
myth_terms = list(set(labels + aliases)) #unisco le label e gli alias, tolgo i duplicati con set e riconverto in lista
len(myth_terms)

4456

In [141]:
#ENDPOINT SPARLQ DI ARCO 
arco_endpoint = "https://dati.cultura.gov.it/sparql"

sparql_arco = SPARQLWrapper(arco_endpoint)
sparql_arco.setReturnFormat(JSON)

In [142]:
# NUMERO TOTALE DEI BENI STORICO ARTISTICI - senza duplicati 
query1 = """
PREFIX arco: <https://w3id.org/arco/ontology/arco/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT (COUNT(DISTINCT ?item) AS ?totalItems)
WHERE {
  ?item rdf:type <https://w3id.org/arco/ontology/arco/HistoricOrArtisticProperty> .
}
"""


sparql_arco.setQuery(query1)
results = sparql_arco.query().convert()

for result in results["results"]["bindings"]:
    print(f"Total Historic or Artistic Properties: {result['totalItems']['value']}")

Total Historic or Artistic Properties: 2258640

In [ ]:
#query pr estrarre i dati dei beni storico artistici i batch 

query2 = f"""
PREFIX arco: <https://w3id.org/arco/ontology/arco/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX a-cd: <https://w3id.org/arco/ontology/context-description/>

SELECT DISTINCT ?item ?label ?title ?date ?description ?historical 
WHERE {{
  ?item rdf:type <https://w3id.org/arco/ontology/arco/HistoricOrArtisticProperty> .

  OPTIONAL {{ ?item rdfs:label ?label }}
  OPTIONAL {{ ?item dc:title ?title }}
  OPTIONAL {{ ?item dc:date ?date }}
  OPTIONAL {{ ?item dc:description ?description }}
  OPTIONAL {{ ?item a-cd:historicalInformation ?historical }}
}}

LIMIT 1000
OFFSET 0

"""

sparql_arco.setQuery(query2)
results = sparql_arco.query().convert()

In [144]:
rows = []

for r in results["results"]["bindings"]:

    rows.append({
        "item": r["item"]["value"] if "item" in r else None,
        "label": r["label"]["value"] if "label" in r else None,
        "title": r["title"]["value"] if "title" in r else None,
        "date": r["date"]["value"] if "date" in r else None,
        #"description": r["description"]["value"] if "description" in r else None,
        #"historical": r["historical"]["value"] if "historical" in r else None
    })

df_arco = pd.DataFrame(rows)
len(df_arco)
#df_arco.head(10)

1000

In [150]:
# nel dataframe uniamo i campi di title e label in un unico campo "name" per facilitare la ricerca
df_arco["search_text"] = (
    df_arco["label"].fillna("") + " " + df_arco["title"].fillna("")
)

df_arco[["label", "title", "search_text"]].head(1000)

,label,title,search_text
0,Arlecchino primordiale. Fine del cinquecento. ...,Arlecchino primordiale. Fine del cinquecento. ...,Arlecchino primordiale. Fine del cinquecento. ...
1,Arlecchino primordiale. Fine del cinquecento. ...,Arlecchino primordiale. Fine del cinquecento. ...,Arlecchino primordiale. Fine del cinquecento. ...
2,"Pulcinella, maschera della Commedia dell'Arte ...","Pulcinella, maschera della Commedia dell'Arte ...","Pulcinella, maschera della Commedia dell'Arte ..."
3,"Pulcinella, maschera della Commedia dell'Arte ...","Pulcinella, maschera della Commedia dell'Arte ...","Pulcinella, maschera della Commedia dell'Arte ..."
4,"Truffaldino, maschera della Commedia dell'Arte...","Truffaldino, maschera della Commedia dell'Arte...","Truffaldino, maschera della Commedia dell'Arte..."
...,...,...,...
995,monogramma di San Bernardino da Siena (scultur...,scultura,monogramma di San Bernardino da Siena (scultur...
996,lampada pensile - bottega toscana (sec. XIX),lampada pensile,lampada pensile - bottega toscana (sec. XIX) l...
997,lampada pensile - bottega toscana (sec. XIX),lampada pensile,lampada pensile - bottega toscana (sec. XIX) l...
998,Santa Caterina da Siena (statuetta devozionale...,statuetta devozionale,Santa Caterina da Siena (statuetta devozionale...
999,Santa Caterina da Siena (statuetta devozionale...,statuetta devozionale,Santa Caterina da Siena (statuetta devozionale...

In [146]:
# Creiamo search_text solo da label e title

import re

# Pre-normalizzazione dei termini (fondamentale)
myth_terms_clean = [
    t.strip()
    for t in myth_terms
    if isinstance(t, str) and t.strip() != ""
]

# Funzione robusta di matching
def find_matched_terms(text, terms_list):
    if not isinstance(text, str):
        return None

    matched = []

    for term in terms_list:
        if re.search(r'\b' + re.escape(term) + r'\b', text):
            matched.append(term)
    
    return ", ".join(matched) if matched else None


# Applica il matching in modo sicuro
df_arco["matched_term"] = df_arco["search_text"].apply(
    lambda text: find_matched_terms(text, myth_terms_clean)
)

# Filtra solo le righe con almeno un match
df_matches = df_arco[df_arco["matched_term"].notna()].copy()

print(f"Righe con almeno 1 match: {len(df_matches)}")

Righe con almeno 1 match: 48

In [147]:
# Verifica i risultati
print(f"Totale beni Arco: {len(df_arco)}")
print(f"Beni con match mitologico: {len(df_matches)}")

Totale beni Arco: 1000
Beni con match mitologico: 48

In [ ]:
#vediamo i risultati
#df_matches

,item,label,title,date,search_text,matched_term
8,https://w3id.org/arco/resource/HistoricOrArtis...,"Studio per Medea, figura femminile a mezzo bus...","Studio per Medea, figura femminile a mezzo bus...",1978-1978,"Studio per Medea, figura femminile a mezzo bus...",Medea
9,https://w3id.org/arco/resource/HistoricOrArtis...,"Studio per Medea, figura femminile a mezzo bus...","Studio per Medea, figura femminile a mezzo bus...",1978-1978,"Studio per Medea, figura femminile a mezzo bus...",Medea
46,https://w3id.org/arco/resource/HistoricOrArtis...,MCMXV - MCMXVIII I fasti del valore e del sacr...,MCMXV - MCMXVIII I fasti del valore e del sacr...,post 1915-ante 1932,MCMXV - MCMXVIII I fasti del valore e del sacr...,Nestore
47,https://w3id.org/arco/resource/HistoricOrArtis...,MCMXV - MCMXVIII I fasti del valore e del sacr...,MCMXV - MCMXVIII I fasti del valore e del sacr...,post 1915-ante 1932,MCMXV - MCMXVIII I fasti del valore e del sacr...,Nestore
160,https://w3id.org/arco/resource/HistoricOrArtis...,Antonio sostenuto da Diomede (stampa smarginat...,stampa smarginata,post 1822-ante 1822,Antonio sostenuto da Diomede (stampa smarginat...,Diomede
161,https://w3id.org/arco/resource/HistoricOrArtis...,Antonio sostenuto da Diomede (stampa smarginat...,stampa smarginata,post 1822-ante 1822,Antonio sostenuto da Diomede (stampa smarginat...,Diomede
166,https://w3id.org/arco/resource/HistoricOrArtis...,"Cristo dal braccio destro schiodato, Gesù Cris...","Cristo dal braccio destro schiodato, Gesù Cris...",ca 1800-ca 1824,"Cristo dal braccio destro schiodato, Gesù Cris...",Teodoro
167,https://w3id.org/arco/resource/HistoricOrArtis...,"Cristo dal braccio destro schiodato, Gesù Cris...","Cristo dal braccio destro schiodato, Gesù Cris...",ca 1800-ca 1824,"Cristo dal braccio destro schiodato, Gesù Cris...",Teodoro
194,https://w3id.org/arco/resource/HistoricOrArtis...,Allegoria della Fede e clipeo con ritratto di ...,stampa,ca 1845-ca 1845,Allegoria della Fede e clipeo con ritratto di ...,Fede
195,https://w3id.org/arco/resource/HistoricOrArtis...,Allegoria della Fede e clipeo con ritratto di ...,stampa,ca 1845-ca 1845,Allegoria della Fede e clipeo con ritratto di ...,Fede
196,https://w3id.org/arco/resource/HistoricOrArtis...,"Il martirio di San Giusto, Studio preparatorio...","Il martirio di San Giusto, Studio preparatorio...",1946-1946,"Il martirio di San Giusto, Studio preparatorio...",Alice
197,https://w3id.org/arco/resource/HistoricOrArtis...,"Il martirio di San Giusto, Studio preparatorio...","Il martirio di San Giusto, Studio preparatorio...",1946-1946,"Il martirio di San Giusto, Studio preparatorio...",Alice
198,https://w3id.org/arco/resource/HistoricOrArtis...,"Il martirio di San Giusto, Studio preparatorio...","Il martirio di San Giusto, Studio preparatorio...",1946-1946,"Il martirio di San Giusto, Studio preparatorio...",Alice
199,https://w3id.org/arco/resource/HistoricOrArtis...,"Il martirio di San Giusto, Studio preparatorio...","Il martirio di San Giusto, Studio preparatorio...",1946-1946,"Il martirio di San Giusto, Studio preparatorio...",Alice
200,https://w3id.org/arco/resource/HistoricOrArtis...,"Motivo decorativo astratto, Modello con rappre...","Motivo decorativo astratto, Modello con rappre...",1977-1977,"Motivo decorativo astratto, Modello con rappre...",Alice
201,https://w3id.org/arco/resource/HistoricOrArtis...,"Motivo decorativo astratto, Modello con rappre...","Motivo decorativo astratto, Modello con rappre...",1977-1977,"Motivo decorativo astratto, Modello con rappre...",Alice
202,https://w3id.org/arco/resource/HistoricOrArtis...,"Motivi decorativi astratti, Dipinto legato al ...","Motivi decorativi astratti, Dipinto legato al ...",1975-1976,"Motivi decorativi astratti, Dipinto legato al ...",Alice
203,https://w3id.org/arco/resource/HistoricOrArtis...,"Motivi decorativi astratti, Dipinto legato al ...","Motivi decorativi astratti, Dipinto legato al ...",1975-1976,"Motivi decorativi astratti, Dipinto legato al ...",Alice
204,https://w3id.org/arco/resource/HistoricOrArtis...,Bozzetto per pannello con motivi decorativi as...,Bozzetto per pannello con motivi decorativi as...,1975-1976,Bozzetto per pannello con motivi decorativi as...,Alice
205,https://w3id.org/arco/resource/HistoricOrArtis...,Bozzetto per pannello con motivi decorativi as...,Bozzetto per pannello con motivi decorativi as...,1975-1976,Bozzetto per pannello con motivi decorativi as...,Alice
206,https://w3id.org/arco/resource/HistoricOrArtis...,"Bozzetto per pannello decorativo, Pannello dec...","Bozzetto per pannello decorativo, Pannello dec...",1975-1976,"Bozzetto per pannello decorativo, Pannello dec...",Alice
207,https://w3id.org/arco/resource/HistoricOrArtis...,"Bozzetto per pannello decorativo, Pannello dec...","Bozzetto per pannello decorativo, Pannello dec...",1975-1976,"Bozzetto per pannello decorativo, Pannello dec...",Alice
208,https://w3id.org/arco/resource/HistoricOrArtis...,"Bozzetto per pannello decorativo edilizio, Boz...","Bozzetto per pannello decorativo edilizio, Boz...",1975-1976,"Bozzetto per pannello decorativo edilizio, Boz...",Alice
209,https://w3id.org/arco/resource/HistoricOrArtis...,"Bozzetto per pannello decorativo edilizio, Boz...","Bozzetto per pannello decorativo edilizio, Boz...",1975-1976,"Bozzetto per pannello decorativo edilizio, Boz...",Alice
210,https://w3id.org/arco/resource/HistoricOrArtis...,"Bozzetto per pannello decorativo, Bozzetto per...","Bozzetto per pannello decorativo, Bozzetto per...",1975-1976,"Bozzetto per pannello decorativo, Bozzetto per...",Alice
211,https://w3id.org/arco/resource/HistoricOrArtis...,"Bozzetto per pannello decorativo, Bozzetto per...","Bozzetto per pannello decorativo, Bozzetto per...",1975-1976,"Bozzetto per pannello decorativo, Bozzetto per...",Alice
212,https://w3id.org/arco/resource/HistoricOrArtis...,"Bozzetto per pannello decorativo astratto, Boz...","Bozzetto per pannello decorativo astratto, Boz...",1975-1976,"Bozzetto per pannello decorativo astratto, Boz...",Alice
213,https://w3id.org/arco/resource/HistoricOrArtis...,"Bozzetto per pannello decorativo astratto, Boz...","Bozzetto per pannello decorativo astratto, Boz...",1975-1976,"Bozzetto per pannello decorativo astratto, Boz...",Alice
214,https://w3id.org/arco/resource/HistoricOrArtis...,"L'Autostrada del Sole, Veduta astratta dell'Au...","L'Autostrada del Sole, Veduta astratta dell'Au...",ante 1961-ante 1961,"L'Autostrada del Sole, Veduta astratta dell'Au...","Sole, Alice"
215,https://w3id.org/arco/resource/HistoricOrArtis...,"L'Autostrada del Sole, Veduta astratta dell'Au...","L'Autostrada del Sole, Veduta astratta dell'Au...",ante 1961-ante 1961,"L'Autostrada del Sole, Veduta astratta dell'Au...","Sole, Alice"
216,https://w3id.org/arco/resource/HistoricOrArtis...,"Motivi astratti ""dorflessiani"", Pannello dipin...","Motivi astratti ""dorflessiani"", Pannello dipin...",ca 1955-ca 1955,"Motivi astratti ""dorflessiani"", Pannello dipin...",Alice
217,https://w3id.org/arco/resource/HistoricOrArtis...,"Motivi astratti ""dorflessiani"", Pannello dipin...","Motivi astratti ""dorflessiani"", Pannello dipin...",ca 1955-ca 1955,"Motivi astratti ""dorflessiani"", Pannello dipin...",Alice
218,https://w3id.org/arco/resource/HistoricOrArtis...,"Studio di figure (""Nuotando sul fondo""), Studi...","Studio di figure (""Nuotando sul fondo""), Studi...",1960-1965,"Studio di figure (""Nuotando sul fondo""), Studi...",Alice
219,https://w3id.org/arco/resource/HistoricOrArtis...,"Studio di figure (""Nuotando sul fondo""), Studi...","Studio di figure (""Nuotando sul fondo""), Studi...",1960-1965,"Studio di figure (""Nuotando sul fondo""), Studi...",Alice
220,https://w3id.org/arco/resource/HistoricOrArtis...,"Cantiere della diga di Assuan, Due pannelli de...","Cantiere della diga di Assuan, Due pannelli de...",1965-1965,"Cantiere della diga di Assuan, Due pannelli de...",Alice
221,https://w3id.org/arco/resource/HistoricOrArtis...,"Cantiere della diga di Assuan, Due pannelli de...","Cantiere della diga di Assuan, Due pannelli de...",1965-1965,"Cantiere della diga di Assuan, Due pannelli de...",Alice
222,https://w3id.org/arco/resource/HistoricOrArtis...,"Senza titolo, Volto femminile faro manichino t...","Senza titolo, Volto femminile faro manichino t...",ante 1955-ante 1955,"Senza titolo, Volto femminile faro manichino t...",Alice
223,https://w3id.org/arco/resource/HistoricOrArtis...,"Senza titolo, Volto femminile faro manichino t...","Senza titolo, Volto femminile faro manichino t...",ante 1955-ante 1955,"Senza titolo, Volto femminile faro manichino t...",Alice
224,https://w3id.org/arco/resource/HistoricOrArtis...,"Senza titolo, Pannello decorativo con vasellam...","Senza titolo, Pannello decorativo con vasellam...",ca 1960-ca 1965,"Senza titolo, Pannello decorativo con vasellam...",Alice
225,https://w3id.org/arco/resource/HistoricOrArtis...,"Senza titolo, Pannello decorativo con vasellam...","Senza titolo, Pannello decorativo con vasellam...",ca 1960-ca 1965,"Senza titolo, Pannello decorativo con vasellam...",Alice
366,https://w3id.org/arco/resource/HistoricOrArtis...,"Ercole (scultura, opera isolata) - ambito Ital...",scultura (opera isolata),200 a.C-0,"Ercole (scultura, opera isolata) - ambito Ital...",Ercole
367,https://w3id.org/arco/resource/HistoricOrArtis...,"Ercole (scultura, opera isolata) - ambito Ital...",scultura (opera isolata),200 a.C-0,"Ercole (scultura, opera isolata) - ambito Ital...",Ercole
538,https://w3id.org/arco/resource/HistoricOrArtis...,"Angelo con globo (scultura, opera isolata) - b...",scultura (opera isolata),1740-1760,"Angelo con globo (scultura, opera isolata) - b...",Angelo
539,https://w3id.org/arco/resource/HistoricOrArtis...,"Angelo con globo (scultura, opera isolata) - b...",scultura (opera isolata),1740-1760,"Angelo con globo (scultura, opera isolata) - b...",Angelo
692,https://w3id.org/arco/resource/HistoricOrArtis...,natività di Gesù (dipinto) by Casolani Alessan...,dipinto,ca 1607-ca 1607,natività di Gesù (dipinto) by Casolani Alessan...,Alessandro
693,https://w3id.org/arco/resource/HistoricOrArtis...,natività di Gesù (dipinto) di Casolani Alessan...,dipinto,ca 1607-ca 1607,natività di Gesù (dipinto) di Casolani Alessan...,Alessandro
804,https://w3id.org/arco/resource/HistoricOrArtis...,Sant'Anna (scultura) - bottega toscana (sex. X...,scultura,1600-1699,Sant'Anna (scultura) - bottega toscana (sex. X...,Anna
805,https://w3id.org/arco/resource/HistoricOrArtis...,Sant'Anna (scultura) - bottega toscana (sex. X...,scultura,1600-1699,Sant'Anna (scultura) - bottega toscana (sex. X...,Anna